name: build
on: [push, pull_request]

jobs:
  full-build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v1
        with:
          php-version: "7.4"
          coverage: pcov
          extensions: dom, json, libxml, mbstring, pdo_sqlite, soap, xml, xmlwriter
          ini-values: assert.exception=1, zend.assertions=1
      - name: "Validate composer.json"
        run: composer validate
      - name: "Setup composer cache"
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: composer-full-build-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-full-build-cache-
      - name: "Install highest dependencies"
        run: composer update --no-interaction --no-ansi --no-progress --no-suggest --prefer-stable
      - name: "Coding standard Php-CS-Fixer checks"
        run: vendor/bin/php-cs-fixer --dry-run -v --config=cs-fixer.php.dist --path-mode=intersection fix src tests
      - name: "Coding standard CodeSniffer checks"
        run: |
          vendor/bin/phpcs --extensions=php --standard=$GITHUB_WORKSPACE/vendor/polymorphine/dev/phpcs.xml src
          vendor/bin/phpcs --extensions=php --standard=$GITHUB_WORKSPACE/vendor/polymorphine/dev/phpcs.xml tests
      - name: "Run PhpUnit tests with coverage"
        run: |
          mkdir -p build/logs
          vendor/bin/phpunit --exclude-group integrated --coverage-clover build/logs/clover.xml
      - name: "Send coverage report to coveralls.io"
        run: vendor/bin/php-coveralls -v
        env:
          COVERALLS_RUN_LOCALLY: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  lowest-build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v1
        with:
          php-version: "7.4"
          coverage: pcov
          extensions: dom, json, libxml, mbstring, pdo_sqlite, soap, xml, xmlwriter
          ini-values: assert.exception=1, zend.assertions=1
      - name: "Setup composer cache"
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: composer-lowest-build-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-lowest-build-cache-
      - name: "Install lowest dependencies"
        run: composer update --no-interaction --no-ansi --no-progress --no-suggest --prefer-stable --prefer-lowest
      - name: "Run PhpUnit tests (no coverage)"
        run: vendor/bin/phpunit --exclude-group integrated --no-coverage
